# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure subscription 1(09596d8b-933e-4093-a627-78cef0237f46)'
    backendAzureRmResourceGroupName: 'my_resource'
    backendAzureRmStorageAccountName: 'hghghghhghg'
    backendAzureRmContainerName: 'hghghghhghg1'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure subscription 1(09596d8b-933e-4093-a627-78cef0237f46)'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Azure subscription 1(09596d8b-933e-4093-a627-78cef0237f46)'
