# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfvalidate
    jobs: 
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure subscription 1(09596d8b-933e-4093-a627-78cef0237f46)'
    backendAzureRmResourceGroupName: 'my_resource'
    backendAzureRmStorageAccountName: 'ravan666'
    backendAzureRmContainerName: 'terra-work'
    backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdeploy
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:    
          - task: TerraformInstaller@1
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Azure subscription 1(09596d8b-933e-4093-a627-78cef0237f46)'
              backendAzureRmResourceGroupName: 'my_resource'
              backendAzureRmStorageAccountName: 'ravan666'
              backendAzureRmContainerName: 'terra-work'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Azure subscription 1(09596d8b-933e-4093-a627-78cef0237f46)'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Azure subscription 1(09596d8b-933e-4093-a627-78cef0237f46)'